from setuptools import setup
from setuptools import find_packages

setup(name='SparseGAMsWithInteractions',
      version='1.0',
      description='Generalized Additive Models with Interactions under L0 sparsity with/without Strong Hierarchy',
      author='Shibal Ibrahim',
      author_email='shibal.ibrahim@gmail.com',
#      url='',
      download_url='https://github.com/ShibalIbrahim/Interpretable-Nonparametric-Additive-Models-with-Structured-Interactions',
      license='MIT',
      install_requires=['descartes==1.1.0',
                        'dill==0.3.3',
                        'fiona==1.8.18',
                        'geopandas==0.8.1',
                        'hyperopt==0.2.5',
                        'ipywidgets==7.5.1',
                        'matplotlib==3.3.2',
                        'notebook==6.1.5',
                        'numpy==1.19.4',
                        'pandas==1.1.4',
                        'patsy==0.5.1',
                        'pyproj==2.6.1.post1',
                        'rpy2==3.3.6',
                        'rtree==0.9.4',
                        'scikit-learn==0.23.2',
                        'scipy==1.5.3',
                        'shapely==1.7.1',
                        'tensorflow-gpu==2.2.0',
                        'tqdm==4.54.1',
                        'xgboost==1.2.0'
                        ],
      package_data={'SparseGAMsWithInteractions': ['README.md']},
      packages=find_packages(),
      python_requires='==3.6.12')
